version: '{build}'
os: Visual Studio 2015 RC
cache: C:\Users\appveyor\.dnx\packages
build_script:
- cmd: >-
    @echo off

    setlocal EnableExtensions

    dnu restore || set errorlevel=1

    dnu build src\Kraken --configuration Release || set errorlevel=1

    set release_notes=

    for /f "delims=" %%i in ('RELEASENOTES.md') do set release_notes=%release_notes% %%i

    exit /b %errorlevel%
test_script:
- cmd: >-
    @echo off

    setlocal EnableExtensions

    cd test\Kraken.Tests

    dnx test || set errorlevel=1

    cd ..\..\

    exit /b %errorlevel%
before_deploy:
- cmd: >-
    @echo off

    setlocal EnableExtensions

    npm install -g bower

    npm install -g gulp

    dnu publish src\Kraken --runtime active --configuration Release --iis-command web-prod || set errorlevel=1	

    nuget pack Kraken.nuspec -NoPackageAnalysis || set errorlevel=1

    appveyor PushArtifact Kraken.*.nupkg -DeploymentName GitHub

    exit /b %errorlevel%
deploy:
- provider: GitHub
  description: $(release_notes)
  auth_token:
    secure: ttUANtrgmx3KYQ8JqCQ1t2FnA8vCEFH9WBlmdGmxoBjSb6o55ZnSoqaKWf2HZLMV
  artifact: GitHub
  draft: false
  prerelease: true
  on:
    appveyor_repo_tag: true